name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GOODREADS_TOKEN: ${{ secrets.GOODREADS_TOKEN }}
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: Latest brain outputs
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          sudo pip install PyGithub
          sudo chmod 777 README.md
          sudo echo -e "### 🧠 Latest changes on [brain.louis030195.com](https://brain.louis030195.com)\n\n$(sudo python3 hack_obsidian.py ${GITHUB_TOKEN})\n\n$(sudo cat README.md)" > README.md

      - run: |
          sudo pip install requests beautifulsoup4
          sudo chmod 777 README.md
          sudo echo -e "### 👋 Favourite daily quotes from readwise.io/@louis\n\n$(sudo python3 hack.py)\n\n$(sudo cat README.md)" > README.md

      - uses: actions/upload-artifact@v1
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
