name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          GOODREADS_TOKEN: ${{ secrets.GOODREADS_TOKEN }}
          GOODREADS_USER_ID: ${{ secrets.GOODREADS_USER_ID }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - name: Memory stream
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
          sudo pip install PyGithub requests beautifulsoup4
          sudo chmod 777 README.md
          sudo echo -e 
          echo "MEMORY_STREAM=\"### 👋 Favourite daily quotes from [readwise.io/@louis](https://readwise.io/@louis)\n$(sudo python3 hack.py)\n\n### 🧠 Latest changes on [brain.louis030195.com](https://brain.louis030195.com)\n$(sudo python3 hack_obsidian.py ${GITHUB_TOKEN})\"" >> $GITHUB_ENV
          sudo python3 - <<EOF
              # Find [START] in README.md and replace it with MEMORY_STREAM
              import re
              import os
              with open('README.md', 'w') as f:
                content = f.read()
                content = re.sub(r'\[START\]', os.environ['MEMORY_STREAM'], content)
                f.write(content)
          EOF
      - uses: actions/upload-artifact@v1
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
